### ISSUE TITLE
Cannot convert URL.

### ISSUE THREAD

**Issue by tuanbs** [mrdaghestani/HtmlToPdfOrImage#1]
Hello author, your demo site works fine with URL, but it doesn't work using your nuget. My code is:

var api = new HtmlToPdfOrImage.Api("99433eae-569c-470d-a763-0a3d0b28ad21", "vmZ2Qryg");
var result = api.Convert("http://subnews.peterapp.com/#/mediaHouse/1/program/1");
File.WriteAllBytes("myfile.pdf", (byte[])result.model);

The result is the blank pdf with url. So I think I did it in a wrong way. Could you tell me how I can generate PDF file from URL which your demo site does. Thanks.

**Comment by mrdaghestani** [comment]
Hello tuanbs,
Let me check, I will comment more as soon as possible.

**Comment by mrdaghestani** [comment]
When you want to convert Url to PDF, you must pass Uri object.
Your code must be like this:

var api = new HtmlToPdfOrImage.Api("99433eae-569c-470d-a763-0a3d0b28ad21", "vmZ2Qryg");
var result = api.Convert(**new Uri(**"http://subnews.peterapp.com/#/mediaHouse/1/program/1" **)**);
System.IO.File.WriteAllBytes(Request.MapPath("~/myfile.pdf"), (byte[])result.model);

**Comment by LuisMemo** [comment]
Does the web service is still working?
I cant generate pdfs :S

**Comment by tuanbs** [comment]
Unfortunately not. Now I use pdfcrowd instead.

**Comment by LuisMemo** [comment]
Thanks

**Comment by mrdaghestani** [comment]
Hello dear,
Unfortunately our server is down. I try to solve this problem in next 3 days.
Thank you for your interest.

**Comment by mrdaghestani** [comment]
Our service is up now.
Sorry for delay.
