### ISSUE TITLE
Working almost perfect

### ISSUE THREAD

**Issue by LuisMemo** [mrdaghestani/HtmlToPdfOrImage#2]
Hi. This tool is very helpfull, It is one of the easiest on the net, and suports a lot of the css styles.
I was using it over VS2013 and was working pretty fine, but since yesterday I had problems to generate the pdf file. The error Im getting is -2146233079, and says something about the server response is not avialable (it is in spanish so Im trying to traslate it). And the Demo Website is not working neigther. :(
I dont know if there is something wrong in my code or is something in the webservice but I tried using the same code you posted in the demo and didnt work out.
Any idea?
Thanks

**Comment by mrdaghestani** [comment]
Hello dear LuisMemo,
Unfortunately our server is down. I try to solve this problem in next 3 days.
Thank you for your interest.

**Comment by mrdaghestani** [comment]
Hi,
Our service is up now.
Sorry for delay.
