### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by tareksharbak** [mrdaghestani/HtmlToPdfOrImage#3]
Hey, I wanna start by thanking you for the great service! I am using your nugget package and API to generate PDF's as invoices for charity events. but it seems that the API and website are down at the moment, is this a temporary thing or do I need to change the library that I'm using?

Thank you in advance!

**Comment by tareksharbak** [comment]
I think I should've been a little patient :) everything seems to be working fine again. Thank you!

**Comment by mrdaghestani** [comment]
Hi Dear, Thank you for using my service.
If you got any problem, I'm here to help you ;)
