### ISSUE TITLE
convert to image cant open.

### ISSUE THREAD

**Issue by zmx312502865** [mrdaghestani/HtmlToPdfOrImage#4]
`System.IO.File.WriteAllBytes(@"C:\\myfile.jpg", (byte[])result.model);`
The  file  of myfile.jpg  is broken...how can i do

**Comment by mrdaghestani** [comment]
What is your content? Do you want to convert a Html page or Url?
Please give me entire code.

**Comment by zmx312502865** [comment]
`var api = new HtmlToPdfOrImage.Api("99433eae-569c-470d-a763-0a3d0b28ad21", "vmZ2Qryg");
            var result = api.Convert("<b>Html to PDF Sample</b>");
            System.IO.File.WriteAllBytes(@"C:\\myfile.jpg", (byte[])result.model);`
from your demo  ..  I want convert a html page  to image....

**Comment by mrdaghestani** [comment]
If you want to create image from html, please use this code:

`var api = new HtmlToPdfOrImage.Api("99433eae-569c-470d-a763-0a3d0b28ad21", "vmZ2Qryg");`
`var result = api.Convert("<b>Html to PDF Sample</b>", new HtmlToPdfOrImage.GenerateSettings
                                                                    {
                                                                        OutputType = HtmlToPdfOrImage.OutputType.Image
                                                                    });`
`System.IO.File.WriteAllBytes(@"C:\\myfile.jpg", (byte[])result.model);`

default of **OutputType** is PDF

**Comment by zmx312502865** [comment]
Thanks,  it is well done
