### ISSUE TITLE
Process behind the conversion

### ISSUE THREAD

**Issue by funzeye** [mrdaghestani/HtmlToPdfOrImage#5]
Hi,
If you don't mind me asking - I was just wondering what method and libraries you are using on your end to convert the html to pdf?
Are you using wkhtmltopdf or something else like phantomjs?

**Comment by amoswzw** [comment]
obviously,wkhtmltopdf

**Comment by mrdaghestani** [comment]
Yes, That's right, I use wkhtmltopdf
and if you don't want to use my api you can install wkhtmltopdf and use this library:
https://github.com/mrdaghestani/HtmlPI

**Comment by funzeye** [comment]
Thanks,
I will look into it. 
great work.
