### ISSUE TITLE
Value cannot be null. Parameter name: bytes

### ISSUE THREAD

**Issue by LuisMemo** [mrdaghestani/HtmlToPdfOrImage#6]
Hello, Mr.
Im having troubles with the pdf's generator, I hope you can give me some ideas.
I have the same code in two diferent servers, one of them works fine but in the other one Im getting this error:  **Value cannot be null. Parameter name: bytes**
I have checked the carpets permissions and looks fine, I can write txt files into this path, and also tried adding **new Uri(...** like someone else asked but its the same.
Hope you can see something Im lossing.
Txs

```
var api = new HtmlToPdfOrImage.Api ("99433eae-569c-470d-a763-0a3d0b28ad21", "vmZ2Qryg");
var result = api.Convert (myHtmlPage);
File.WriteAllBytes (PathAndFile.pdf, (byte []) result.model);
```

**Comment by mrdaghestani** [comment]
Hi dear,
Your code looks fine, as you said this is working in one of your two servers, probably your second server doesn't have access to my Api server. This component is using an API in an Iranian Data Center and maybe it's hard for your second server to connect the API. (Internet in Iran sucks)
Try to open [HtmlToPdf website](http://htmltopdforimage.com/) in your server.
If it doesn't, it's because of internet connection or DNS problem but if it does, let me know and we will find another solution.
Tnx

**Comment by mrdaghestani** [comment]
Let's check this first, What is the value of 'myHtmlPage' ?
Is it string of a Html Content or an Uri of a page?

**Comment by LuisMemo** [comment]
Thank, Mr.
I opened the page in the server and works fine. The value of **myHtmlPage** is the html from an aspx, but I changed with `<p>Something</p>` and it is the same error.
I guess it has to be with the operative sistem on the server or some update
Im gonna try with 

`var converter = new HtmlPI.HtmlConverter ();
var filePath = converter.Convert (new HtmlPI.GenerateSettings
{
      HtmlFileContent = "<b>Bold Text</b><br /><br /><i>Italic Text</i>",
      OutputType = HtmlPI.OutputType.PDF
});`

hope it works
Txs

**Comment by mrdaghestani** [comment]
Hello again,
Are you using **HtmlToPdfOrImage** or **HtmlPI**?
This has two different methods...!
As I wrote in **read me**, if you are using **Html PI**:
`
First you have to install wkhtmltopdf on application server (your developing system or client's systems)
`
Probably this is the problem that your last code does't work.

But about your first code, I try it in my PC and it works.
`
var api = new HtmlToPdfOrImage.Api("99433eae-569c-470d-a763-0a3d0b28ad21", "vmZ2Qryg");
var result = api.Convert("<b>Hello</b>");
File.WriteAllBytes(@"c:\hello.pdf", (byte[])result.model);
`
But before running this, I had to update **Json.NET** from NuGet.

**Comment by LuisMemo** [comment]
Hey, man.
Thanks for your time. I tried both of them, **HtmlToPdfOrImage** and **HtmlPI** and any of those worked. In my computer and in the tests server everything works just amazing, but in the production server sadly something is wrong. I think it is something about updates or configuration issues in that especific server. I'm gonna use an other dll trying to make it works in that freaking server.
Thank you, very much.
Salutes from Mexico!!

**Comment by mrdaghestani** [comment]
You're Welcome, Good Luck my friend. ;)
