### ISSUE TITLE
The service is down!

### ISSUE THREAD

**Issue by vxnsbir1ugsp** [mrdaghestani/HtmlToPdfOrImage#9]
For some reason the website is down and I cannot use this awesome wrapper. Do you have any idea if it will be back soon?

**Comment by mrdaghestani** [comment]
Dear vxnsbir1ugsp,
Sorry for the server break down. I am moving my application to another server and It will be OK in the next 3 days.

**Comment by vxnsbir1ugsp** [comment]
I need this urgently. Thanks!

**Comment by vxnsbir1ugsp** [comment]
Any progress on this one? Thanks!

**Comment by mrdaghestani** [comment]
Dear vxnsbir1ugsp,
I'm afraid that it's not possible for me to serve it anymore.
You can use [HtmlPI](https://github.com/mrdaghestani/HtmlPI) instead of this service. It has got the same functionality but you need to install wkhtmltopdf tool on your server.
Thanks.
